services:
    postgres-db:
        image: postgres:16-alpine
        environment:
            - POSTGRES_DB=site
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
            - pg-data:/var/lib/postgresql/data
        ports:
            - 9500:5432
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres -d site" ]
            interval: 2s
            timeout: 1s
            retries: 5

    site:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            DB_URI: "postgresql://postgres:postgres@postgres-db:5432/site"
        depends_on:
            postgres-db:
                condition: service_healthy
        ports:
            - 8000:8000
        volumes:
            - .:/app


# Persistent data storage volumes
volumes:
    pg-data:
